# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3c85b936-8d2e-4809-b452-ea34512afa47";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/e2943a07-2529-4307-a35d-85b3262fb9de";

  fileSystems."/.swapvol" =
    { device = "/dev/disk/by-uuid/3c85b936-8d2e-4809-b452-ea34512afa47";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B0DE-3562";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3c85b936-8d2e-4809-b452-ea34512afa47";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/3c85b936-8d2e-4809-b452-ea34512afa47";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };



  fileSystems."/home/WiredDesdpy/SSD-240GB" =
    { device = "/dev/disk/by-uuid/6437da46-dfec-45f9-bd3d-54f6da48461a";
      fsType = "ext4";
      options = [ "nofail" ];
    };


  # Create ~/.smbcredentials first
  fileSystems."/home/WiredDesdpy/TrueNAS/Sascha" =
    { device = "//10.10.20.20/Sascha";
      fsType = "cifs";
      options = [ "credentials=/home/WiredDesdpy/.smbcredentials" "uid=1000" "gid=100" "nofail" ];
    };

  fileSystems."/home/WiredDesdpy/TrueNAS/Aireen" =
    { device = "//10.10.20.20/Aireen";
      fsType = "cifs";
      options = [ "credentials=/home/WiredDesdpy/.smbcredentials" "uid=1000" "gid=100" "nofail" ];
    };

  fileSystems."/home/WiredDesdpy/TrueNAS/Nanay" =
    { device = "//10.10.20.20/Nanay";
      fsType = "cifs";
      options = [ "credentials=/home/WiredDesdpy/.smbcredentials" "uid=1000" "gid=100" "nofail" ];
    };

  fileSystems."/home/WiredDesdpy/TrueNAS/Familienfotos_und_videos" =
    { device = "//10.10.20.20/Familienfotos_und_videos";
      fsType = "cifs";
      options = [ "credentials=/home/WiredDesdpy/.smbcredentials" "uid=1000" "gid=100" "nofail" ];
    };

  fileSystems."/home/WiredDesdpy/TrueNAS/Database" =
    { device = "//10.10.20.20/Database";
      fsType = "cifs";
      options = [ "credentials=/home/WiredDesdpy/.smbcredentials" "uid=1000" "gid=100" "nofail" ];
    };



  fileSystems."/home/WiredDesdpy/Desktop" =
    { device = "//10.10.20.20/Sascha/Desktop";
      fsType = "cifs";
      options = [ "credentials=/home/WiredDesdpy/.smbcredentials" "uid=1000" "gid=100" "nofail" ];
    };

  fileSystems."/home/WiredDesdpy/Documents" =
    { device = "//10.10.20.20/Sascha/Documents";
      fsType = "cifs";
      options = [ "credentials=/home/WiredDesdpy/.smbcredentials" "uid=1000" "gid=100" "nofail" ];
    };
    
  fileSystems."/home/WiredDesdpy/Downloads" =
    { device = "//10.10.20.20/Sascha/Downloads";
      fsType = "cifs";
      options = [ "credentials=/home/WiredDesdpy/.smbcredentials" "uid=1000" "gid=100" "nofail" ];
    };

  fileSystems."/home/WiredDesdpy/Music" =
    { device = "//10.10.20.20/Sascha/Music";
      fsType = "cifs";
      options = [ "credentials=/home/WiredDesdpy/.smbcredentials" "uid=1000" "gid=100" "nofail" ];
    };

  fileSystems."/home/WiredDesdpy/Pictures" =
    { device = "//10.10.20.20/Sascha/Pictures";
      fsType = "cifs";
      options = [ "credentials=/home/WiredDesdpy/.smbcredentials" "uid=1000" "gid=100" "nofail" ];
    };

  fileSystems."/home/WiredDesdpy/Videos" =
    { device = "//10.10.20.20/Sascha/Videos";
      fsType = "cifs";
      options = [ "credentials=/home/WiredDesdpy/.smbcredentials" "uid=1000" "gid=100" "nofail" ];
    };

  fileSystems."/home/WiredDesdpy/Public" =
    { device = "//10.10.20.20/Sascha/Public";
      fsType = "cifs";
      options = [ "credentials=/home/WiredDesdpy/.smbcredentials" "uid=1000" "gid=100" "nofail" ];
    };

  fileSystems."/home/WiredDesdpy/Templates" =
    { device = "//10.10.20.20/Sascha/Templates";
      fsType = "cifs";
      options = [ "credentials=/home/WiredDesdpy/.smbcredentials" "uid=1000" "gid=100" "nofail" ];
    };

  # Optional: Change Locations in KDE Plasma to the server and delete local directories

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
